-- Migration: 004_ai_inventory_system
--
-- INTENTIONALLY EMPTY — the schema lives once, in 004b_ai_inventory_system.sql.
--
-- History: the original 004 was renamed to 004b in 21a6b2477 (2026-04-04); a
-- byte-identical copy under this un-suffixed name came back in e920eb231
-- (2026-05-02). Both names are recorded in production's schema_migrations
-- (backfilled by 083 on 2026-06-03, verified 2026-09-14), so neither file may
-- be deleted: a recorded name must keep a file, or a restore-from-backup audit
-- reads it as a migration that vanished. `sort -V` applies 004b before this
-- file, so on a from-zero replay every object already exists when this runs.
-- The body was removed 2026-09-14 so the 402 lines of DDL exist exactly once.
