-- Migration: 005_messaging_system
--
-- INTENTIONALLY EMPTY — the schema lives once, in 005c_messaging_system.sql.
--
-- History: the original 005 was renamed to 005c in 21a6b2477 (2026-04-04); a
-- byte-identical copy under this un-suffixed name came back in e920eb231
-- (2026-05-02). Both names are recorded in production's schema_migrations
-- (backfilled by 083 on 2026-06-03, verified 2026-09-14), so neither file may
-- be deleted: a recorded name must keep a file, or a restore-from-backup audit
-- reads it as a migration that vanished. `sort -V` applies 005c before this
-- file. Until 2026-09-14 this copy had to be SKIPPED by migration-order.sh —
-- its three CREATE TRIGGER statements were unguarded, so a second application
-- aborted the from-zero replay. Empty, it needs no skip list at all.
